// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2qfERBvszQYlWmMiUXZs-yI8j2QmGaWk',
    appId: '1:209027813602:web:c1fd90007c749f20644ebb',
    messagingSenderId: '209027813602',
    projectId: 'weather-project-44dfb',
    authDomain: 'weather-project-44dfb.firebaseapp.com',
    storageBucket: 'weather-project-44dfb.appspot.com',
    measurementId: 'G-MWMKGCGDLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Wf5eOUTrBFnool7P-C18xKtSH_9gKds',
    appId: '1:209027813602:android:cb851aeb6e064b29644ebb',
    messagingSenderId: '209027813602',
    projectId: 'weather-project-44dfb',
    storageBucket: 'weather-project-44dfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_LJFOQlpgpDbu8D9OtYYX33fnP2Ofe4k',
    appId: '1:209027813602:ios:ac48ddcac6d6aff0644ebb',
    messagingSenderId: '209027813602',
    projectId: 'weather-project-44dfb',
    storageBucket: 'weather-project-44dfb.appspot.com',
    iosBundleId: 'com.example.weatherProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_LJFOQlpgpDbu8D9OtYYX33fnP2Ofe4k',
    appId: '1:209027813602:ios:ac48ddcac6d6aff0644ebb',
    messagingSenderId: '209027813602',
    projectId: 'weather-project-44dfb',
    storageBucket: 'weather-project-44dfb.appspot.com',
    iosBundleId: 'com.example.weatherProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2qfERBvszQYlWmMiUXZs-yI8j2QmGaWk',
    appId: '1:209027813602:web:bb1f739b8b5ae766644ebb',
    messagingSenderId: '209027813602',
    projectId: 'weather-project-44dfb',
    authDomain: 'weather-project-44dfb.firebaseapp.com',
    storageBucket: 'weather-project-44dfb.appspot.com',
    measurementId: 'G-TG9VZNK5NJ',
  );
}
